package main

import (
	"fmt"
	"log"
	"net/http"
)

func main() {
	dlinput(2020, 8)
}

func dlinput(day, year int) {

	// Generated by curl-to-Go: https://mholt.github.io/curl-to-go

	// curl https://adventofcode.com/2020/day/8/input -o input.txt -H "Cookie: session=53616c7465645f5fe000053ab57034a6bd01cf48eb79d81a2df930e74713ca3a42d406d87d0620bd4eacacd04a21248c"

	url := fmt.Sprintf("https://adventofcode.com/%d/day/%d/input", day, year)

	req, err := http.NewRequest("GET", url, nil)
	if err != nil {
		log.Fatal(err)
	}
	req.Header.Set("Cookie", "session=53616c7465645f5fe000053ab57034a6bd01cf48eb79d81a2df930e74713ca3a42d406d87d0620bd4eacacd04a21248c")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		log.Fatal(err)
	}
	defer resp.Body.Close()

}
